In [ ]:
import pandas as pd
import os
from google.colab import drive 
import numpy as np

drive.mount('/content/drive', force_remount=True)
os.chdir('/content/drive/Shared drives/Capstone Team 15 Drive/Work/Data/')


Mounted at /content/drive


In [ ]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk
import operator
nltk.download('stopwords')
nltk.download('punkt')
stop_words = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
df = pd.read_excel('Sample Walmart data.xlsx')
df.head()

Parent  CausedBy  ...                       _ts          _uts
0    NaN       NaN  ...  2021-01-18T22:09:01.967Z  1.611008e+09
1    NaN       NaN  ...  2021-01-17T22:17:26.886Z  1.610922e+09
2    NaN       NaN  ...  2021-01-16T14:40:08.997Z  1.610808e+09
3    NaN       NaN  ...  2021-01-16T14:40:08.997Z  1.610808e+09
4    NaN       NaN  ...  2021-01-16T14:40:08.997Z  1.610808e+09

[5 rows x 133 columns]

In [ ]:
np.array(df.notna().sum())

array([ 493,    0, 4974, 4974,    0,    0, 4974, 4974, 4974, 4974, 4974,
       4974,    1,    3,   51, 4839, 4974, 1813,    0, 4974,  496, 4974,
          5, 4974, 4974,  373, 4247,    0,    0,    0, 4972,    0,   46,
          0,   23,   51,  747, 4974,    0, 4974, 3360,    0,   49,  141,
       4974, 3067,    3, 4802,   42, 4957, 4957, 1454, 3286, 4957,    9,
          0, 4957, 4957, 4957,  315,    0, 4944, 4957,   84, 4957, 3468,
       4957, 3902,    0, 4957, 4957, 1303, 4230, 3788,    0,    0,    0,
          1,    0, 4957, 4957,    4, 4957,  142, 3972,    0,    0,    0,
       2666, 4456, 1851, 4284, 4275, 4954, 4230, 4588, 4230, 4058, 4957,
       4950, 4957, 4957,  442, 4957,  652,    0, 4735, 4957,   42,    2,
       4318, 4957,    0, 4957, 4957,    0,    1,   20, 1569,    0,   33,
       4844, 4744, 4957, 4957, 4957, 4957, 4957, 4957,  213, 4957, 4957,
       4957])

In [ ]:
df['UCiClassName'].value_counts()

Business Application           1188
Self-Checkout                   470
Application                     359
POS Register                    321
Debit Reader                    222
                               ... 
Video Teleconference Device       1
Virtualization Server             1
Mechanization Crane               1
Workflow Jobs                     1
Power Generator                   1
Name: UCiClassName, Length: 97, dtype: int64

In [ ]:
sub = df[['GroupList', 'UStepsToReplicate', 'ApprovalSet',
        'ShortDescription', 'UServiceLevel', 'CorrelationDisplay',
        'WorkStart', 'AdditionalAssigneeList', 'UWorkaround',
        'UOpenedFrom', 'Notify', 'ServiceOffering', 'SysClassName',
        'ClosedBy', 'FollowUp', 'ParentIncident', 'ReopenedBy',
        'ReassignmentCount', 'AssignedTo', 'SlaDue',
        'CommentsAndWorkNotes', 'URequestedItem', 'Escalation',
        'UponApproval', 'CorrelationId', 'UKnowledgeId', 'UTaskCost']]

In [ ]:
sub.head()

GroupList  UStepsToReplicate  ...    UKnowledgeId UTaskCost
0        NaN                NaN  ...  KB0972295 v1.0       0.0
1        NaN                NaN  ...             NaN       0.0
2        NaN                NaN  ...             NaN       0.0
3        NaN                NaN  ...             NaN       0.0
4        NaN                NaN  ...             NaN       0.0

[5 rows x 27 columns]

SysClassName - Incidents
Notify - Do Not Notify

In [ ]:
sub2 = sub.dropna(how='all', axis=1)
sub2.head()

ShortDescription  ... UTaskCost
0  2019-06-24 14:05:17|GLOBAL|SUB:- Alarm:The job...  ...       0.0
1  SNAP orders not being dispensed because of equ...  ...       0.0
2                 HO-OLCM QA DB not able to connect.  ...       0.0
3  FTE field had incorrect values for some had >1...  ...       0.0
4                                Voice device repair  ...       0.0

[5 rows x 20 columns]

In [ ]:
def costum_tokenize(text):
  try:
    text = re.sub('\W+',' ', text)
    text = word_tokenize(text)
  except TypeError:
    text = 'NaN'
  
  return text

def freq_count(col):
  frq_dic = {}
  for lst in col:
    for i in lst:
      if i not in stop_words and i.isalpha():
        if i in frq_dic:
          frq_dic[i] += 1
        else:
          frq_dic[i] = 1
  return frq_dic

def freq_count2(col):
  frq_dic = {}
  for lst in col:
    for i in lst:
      if i not in stop_words:
        if i in frq_dic:
          frq_dic[i] += 1
        else:
          frq_dic[i] = 1
  return frq_dic


In [ ]:
sub2['tokenized_SD'] = sub2['ShortDescription'].apply(costum_tokenize)

NameError: ignored

# New Section

In [ ]:
frq = freq_count(sub2['tokenized_SD'])
df_frq = pd.DataFrame(columns = ['words', 'counts'])

df_frq['words'] = frq.keys()
df_frq['counts'] = frq.values()

In [ ]:
df_frq.sort_values(by = 'counts', ascending=False)[:20]

In [ ]:
sub2['CorrelationDisplay'].unique()
len(sub2['CorrelationDisplay']) - sub2['CorrelationDisplay'].isna().sum() == len(sub2['CorrelationDisplay'].unique()) 

False

In [ ]:
sub2['AdditionalAssigneeList'].unique()

array([nan, 'Jose Gaitan (Vendor)', 'William Leon (Vendor)',
       'Billi Martinez (Vendor)', 'Manuel Canal Ortega'], dtype=object)

In [ ]:
sub2['UWorkaround'].unique()

array([nan, 'Utility | Not Applicable | DiskSpace | Utility | 1',
       'No issue',
       'Ticket  | CC | Reported label already released by DC.',
       'Escalonado por Leandro de Carvalho <Leandro.Carvalho@big.com.br>',
       'Closing remotely, since the issue is resolved. Confirmed via screenshot',
       'utility',
       'Pager | Customer Request | Request to update status of damaged load',
       '### Application | System generated the put-away moves for the slot even when slot has less height and put on hold ###',
       '.',
       'YMS | Ticket | Customer Request | Status Code | Trailer status code RF was added through the SNOW request submitted by site but the application preference and YMS Cache were not refreshed/reloaded due to which it was not available for users in Trailer Edit screen.',
       'Finance | GBS_EAS | 3422_FBB1 |3',
       'YMS | Ticket | Application | Disk space | YMS Support removed the files manually and also added the path /u/tomee/yms/global/WebMoni

In [ ]:
len(sub2['UOpenedFrom']) - sub2['UOpenedFrom'].isna().sum() == len(sub2['UOpenedFrom'].unique()) 

False

In [ ]:
sub2['Notify'].unique()

array(['Do Not Notify'], dtype=object)

In [ ]:
sub2['SysClassName'].unique()

array(['Incident'], dtype=object)

In [ ]:
sub2['ClosedBy'].value_counts()

Service NCR                         795
TGCI Incident Service                64
Service Event                        58
Service XCall                        46
Nancy Tenorio Garcia                 35
                                   ... 
Andrey Lopez                          1
Daniel Cisneros - DCISNER.s06234      1
Gopinath Manickavel                   1
Eduardo Rojas                         1
Cecil Kruel                           1
Name: ClosedBy, Length: 1254, dtype: int64

In [ ]:
sub2['ParentIncident'].value_counts()

INC19471171    6
INC19629395    4
INC19468096    3
INC19143044    3
INC19747739    3
INC19961470    3
INC19826249    3
INC19559062    2
INC19569424    2
INC19489452    2
INC19541336    2
INC19828590    1
INC19601317    1
INC19972274    1
INC16552169    1
INC17595480    1
INC14353834    1
INC19961471    1
INC15234561    1
INC19693475    1
INC19608320    1
INC19576460    1
INC19347669    1
INC19815037    1
INC19765607    1
INC16633873    1
INC19840441    1
Name: ParentIncident, dtype: int64

In [ ]:
sub2['ReopenedBy'].value_counts()

Service XCall                              27
Service NCR                                 4
T South - tks0006.s04778                    2
J Butler - jlbutle.s04660                   2
Fabiola Souza Valtierra                     1
                                           ..
Dana Jackson                                1
Brandyl Pfander                             1
Marija Markovic - Vendor                    1
Omar Agustin Cabriales - OCABRIA.s04915     1
Michael Hampton                             1
Name: ReopenedBy, Length: 110, dtype: int64

In [ ]:
sub2['ReassignmentCount'].value_counts()

0     2847
1     1155
2      580
3      200
4       71
5       45
6       25
7       16
8       13
9       10
10       6
11       3
23       1
16       1
12       1
Name: ReassignmentCount, dtype: int64

In [ ]:
sub2['AssignedTo'].value_counts()

Service NCR                                365
Karthik Gopinath                            30
Jesse Darr                                  23
Miguel Angel Gonzalez Estrada  (Vendor)     22
Afjal Ali Khan Patan - Vendor               21
                                          ... 
Dejan Matic - Vendor                         1
Satyala Bapuji - Vendor                      1
Madhavan Ayyappan - Vendor                   1
Tomohiro Kanaya - Vendor                     1
Priya Shanmuga - Vendor                      1
Name: AssignedTo, Length: 1351, dtype: int64

In [ ]:
sub2['SlaDue'].value_counts()

2020-09-01T00:00:00.000Z    1
2020-06-10T00:00:00.000Z    1
2020-05-28T00:00:00.000Z    1
Name: SlaDue, dtype: int64

In [ ]:
import re

In [ ]:
sub2['CommentsAndWorkNotes'][5].split('\n')

['07-27-2019 15:22:24 - Service XCall (Work notes)',
 'USER INFORMATION:',
 'User: JEP006J.s06929',
 'Facility: 6929',
 'Country: US',
 'Email: jep006j.s06929.us@wal-mart.com',
 'Secondary Contact: jeremie pitts',
 'Contact Phone: 254-718-0412',
 'FORM INFORMATION:',
 '',
 'TRACE Options:---Dot Com Order Issues - Dot Com is Allowing Customers to Place Alcohol Orders Illegally',
 'Issue Details:---Submitting a ticket to see if there is a way to block off substitutions for alcohol on the website,  when a customer is making an order. The website is giving the customers the option to ask for substitutions when ordering alcohol in which when we are picking the order, and are out of the alcohol the customer wants, it is telling us to substitute and in some instances even telling us a suggested subs, even though we cannot substitute per OBW. With allowing the customer to say the want substitutions on alcohol items, it is giving a false sense that they are going to receive an item when we are 

In [ ]:
re.sub('\W+',' ', sub2['CommentsAndWorkNotes'][1])

'07 04 2019 09 54 57 Service XCall Work notes USER INFORMATION User DMW007V s01525 Facility 1525 Country US Email dmw007v s01525 us wal mart com Secondary Contact Diana White Contact Phone 804 317 4714 FORM INFORMATION TRACE Options SNAP Order not not found Issue Details SNAP orders not being dispensed because of equipment not pairing Error Message Not transmitting Device Type TC70 Order Number 7543190566872 Is this for a single order or multiple Multiple'

In [ ]:
sub2['tokenized_CWN'] = sub2['CommentsAndWorkNotes'].apply(costum_tokenize)
frq2 = freq_count2(sub2['tokenized_CWN'])
df_frq2 = pd.DataFrame(columns = ['words', 'counts'])

df_frq2['words'] = frq2.keys()
df_frq2['counts'] = frq2.values()

df_frq2.sort_values(by = 'counts', ascending=False)[:20]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


words  counts
507           12   37314
602         2020   34562
121   Additional   22460
122     comments   22451
9           Work   19489
7        Service   19482
10         notes   19480
114           01   18144
1927         NCR   15799
116         2021   14609
7955        null   14282
65        Vendor   10583
267            0    9826
258           11    9301
177           10    9169
3048    Dispatch    8041
616           de    7340
132           14    7307
25           com    7272
115           15    7246

In [ ]:
sub2.drop(columns = ['tokenized_CWN'])

ShortDescription  ...                                       tokenized_SD
0     2019-06-24 14:05:17|GLOBAL|SUB:- Alarm:The job...  ...  [2019-06-24, 14:05:17|GLOBAL|SUB, :, -, Alarm,...
1     SNAP orders not being dispensed because of equ...  ...  [SNAP, orders, not, being, dispensed, because,...
2                    HO-OLCM QA DB not able to connect.  ...       [HO-OLCM, QA, DB, not, able, to, connect, .]
3     FTE field had incorrect values for some had >1...  ...  [FTE, field, had, incorrect, values, for, some...
4                                   Voice device repair  ...                            [Voice, device, repair]
...                                                 ...  ...                                                ...
4969  GLUS234U WMS1 Details : 9105 GLUS234U Batch-Jo...  ...  [GLUS234U, WMS1, Details, :, 9105, GLUS234U, B...
4970  Modify the ACL to add INTL-View so that ANY pe...  ...  [Modify, the, ACL, to, add, INTL-View, so, tha...
4971  SCO Availability - v20.2.18,SN:18291522504171:CSM  ...  [SCO, Availability, -, v20.2.18, ,, SN:1829152...
4972  Unable to connect to server || Site is unable ...  ...  [Unable, to, connect, to, server, ||, Site, is...
4973  ESB0024_EAM_SITEMASTER|US|1|ESB.WTX.ERR.000 fa...  ...  [ESB0024_EAM_SITEMASTER|US|1|ESB.WTX.ERR.000, ...

[4974 rows x 21 columns]

In [ ]:
sub2['URequestedItem'].unique()

array([nan, 'RITM4719977', 'RITM7255889', 'RITM7885580', 'RITM8057947',
       'RITM8116596', 'RITM7979845', 'RITM7866023', 'RITM7988261',
       'RITM7921983', 'RITM7938156', 'RITM8065447', 'RITM8099376',
       'RITM7937841', 'RITM7946925', 'RITM8047258', 'RITM3721770',
       'RITM3810008', 'RITM7870800', 'RITM8054717', 'RITM7392218',
       'RITM7828795', 'RITM8260294', 'RITM7831806', 'RITM7864584',
       'RITM7879045', 'RITM7918736', 'RITM7892809', 'RITM7912087',
       'RITM7952817', 'RITM7932928', 'RITM8023994', 'RITM8033137',
       'RITM8036009', 'RITM8074574', 'RITM8074672', 'RITM0801361',
       'RITM0802470', 'RITM1054967', 'RITM1188177', 'RITM1836477',
       'RITM2098000', 'RITM2123202'], dtype=object)

In [ ]:
sub2['Escalation'].unique()

array(['Normal', nan], dtype=object)

In [ ]:
sub2['UponApproval'].unique()

array(['Proceed to Next Task', nan], dtype=object)

In [ ]:
sub2['CorrelationId'].unique()

array([nan, 'INC000002985385', 'INC000004823137', ..., 'INC000006302975',
       'INC000006439807', 'INC000006510256'], dtype=object)

In [ ]:
sub2['UKnowledgeId'].unique()

array(['KB0972295 v1.0', nan, 'KB0666072 v1.0', ..., 'KB1110863 v1.0',
       'KB0062718 v4.0', 'KB0059600 v1.0'], dtype=object)

In [ ]:
sub2['UTaskCost'].unique()

array([ 0., nan])